'use strict';
const { isKnownBrand } = require('../lib/brandCheck');

/**
 * $bssensi <device> [RAM]GB <Android|iOS>
 * Generates Blood Strike sensitivity settings.
 *
 * Blood Strike sensitivity sliders: 0 – 100
 *  - Camera (hip-fire)
 *  - ADS: Red Dot, 2x, 3x, 4x, 6x, Sniper
 *  - Gyroscope (same slots)
 */

const USAGE =
    `🎮 *BLOOD STRIKE SENSITIVITY*\n\n` +
    `Usage: *$bssensi <device> [RAM]GB <Android|iOS>*\n\n` +
    `Examples:\n` +
    `• $bssensi Samsung S23 Ultra 12GB Android\n` +
    `• $bssensi iPhone 15 Pro Max iOS\n` +
    `• $bssensi POCO X6 Pro Android\n\n` +
    `_RAM is optional — defaults to 6 GB if not given_`;

function rand(min, max) { return min + Math.floor(Math.random() * (max - min + 1)); }

function generateBS(ram, isIOS) {
    const tier = ram >= 12 ? 0 : ram >= 8 ? 1 : ram >= 6 ? 2 : 3;

    // Camera (hip-fire) — 0-100
    const camBase = [70, 65, 60, 55][tier];

    // ADS base — 0-100
    const adsBase = [60, 55, 50, 45][tier];

    // Gyroscope base — 0-100
    const gyroBase = isIOS
        ? [85, 80, 75, 68][tier]
        : [90, 85, 78, 70][tier];

    return {
        camera: rand(camBase, camBase + 8),

        adsRedDot:  rand(adsBase,      adsBase + 6),
        ads2x:      rand(adsBase - 10, adsBase - 4),
        ads3x:      rand(adsBase - 18, adsBase - 10),
        ads4x:      rand(adsBase - 25, adsBase - 16),
        ads6x:      rand(adsBase - 33, adsBase - 24),
        adsSniper:  rand(adsBase - 42, adsBase - 32),

        gyroCamera:  rand(gyroBase,      gyroBase + 8),
        gyroRedDot:  rand(gyroBase - 10, gyroBase - 2),
        gyro2x:      rand(gyroBase - 20, gyroBase - 12),
        gyro3x:      rand(gyroBase - 30, gyroBase - 20),
        gyro4x:      rand(gyroBase - 38, gyroBase - 28),
        gyro6x:      rand(gyroBase - 48, gyroBase - 38),
        gyroSniper:  rand(gyroBase - 58, gyroBase - 46),
    };
}

async function bsSensiCommand(sock, chatId, message, userMessage) {
    try {
        const args = userMessage.replace(/^\.bssensi\s*/i, '').trim();
        if (!args) return sock.sendMessage(chatId, { text: USAGE }, { quoted: message });

        const platformMatch = args.match(/\b(android|ios|iphone|ipad)\b/i);
        if (!platformMatch) {
            return sock.sendMessage(chatId, {
                text: `❌ Platform not found. End with *Android* or *iOS*.\n\n${USAGE}`
            }, { quoted: message });
        }

        const platform = platformMatch[0];
        const isIOS    = /ios|iphone|ipad/i.test(platform);
        const ramMatch = args.match(/(\d+)\s*gb/i);
        const ram      = ramMatch ? parseInt(ramMatch[1]) : 6;

        const deviceName = args
            .replace(/\d+\s*gb/i, '')
            .replace(/\b(android|ios|iphone|ipad)\b/i, '')
            .replace(/\s+/g, ' ').trim() || 'Unknown Device';

        if (!isKnownBrand(args)) {
            return sock.sendMessage(chatId, {
                text: `❌ *"${deviceName}"* doesn't look like a real phone model.\n\nPlease use your actual device name.\nExamples: *Samsung S23 Ultra*, *iPhone 15 Pro Max*, *POCO X6 Pro*`
            }, { quoted: message });
        }

        const s = generateBS(ram, isIOS);

        // Clamp all values to 0-100
        for (const k of Object.keys(s)) {
            s[k] = Math.min(100, Math.max(0, s[k]));
        }

        const text = [
            `🎮 *BLOOD STRIKE SENSITIVITY*`,
            `━━━━━━━━━━━━━━━━━━━━`,
            `📱 *${deviceName.toUpperCase()}*`,
            `💾 ${ramMatch ? `RAM: ${ram}GB  •  ` : ''}${isIOS ? 'iPhone/iOS' : 'Android'}`,
            `━━━━━━━━━━━━━━━━━━━━`,
            ``,
            `📷 *CAMERA (Hip-Fire)* → *${s.camera}*`,
            ``,
            `🎯 *ADS SENSITIVITY*`,
            `   🔴 Red Dot  → *${s.adsRedDot}*`,
            `   🔭 2x Scope → *${s.ads2x}*`,
            `   🔭 3x Scope → *${s.ads3x}*`,
            `   🔭 4x Scope → *${s.ads4x}*`,
            `   🔭 6x Scope → *${s.ads6x}*`,
            `   🎯 Sniper   → *${s.adsSniper}*`,
            ``,
            `🌀 *GYROSCOPE SENSITIVITY*`,
            `   Camera      → *${s.gyroCamera}*`,
            `   Red Dot     → *${s.gyroRedDot}*`,
            `   2x Scope    → *${s.gyro2x}*`,
            `   3x Scope    → *${s.gyro3x}*`,
            `   4x Scope    → *${s.gyro4x}*`,
            `   6x Scope    → *${s.gyro6x}*`,
            `   Sniper      → *${s.gyroSniper}*`,
            ``,
            `━━━━━━━━━━━━━━━━━━━━`,
            `_Generated by Daratech_ 🫶`,
        ].join('\n');

        await sock.sendMessage(chatId, { text }, { quoted: message });

    } catch (err) {
        console.error('[bssensi]', err.message);
        await sock.sendMessage(chatId, { text: '❌ Failed to generate sensitivity.' }, { quoted: message });
    }
}

module.exports = bsSensiCommand;
