'use strict';
const { isKnownBrand } = require('../lib/brandCheck');

/**
 * $codmsensi <device> [RAM]GB <Android|iOS>
 * Generates Call of Duty Mobile sensitivity settings.
 *
 * CODM sensitivity sliders: 0 – 200
 *  - Firing Camera (hip-fire)
 *  - ADS: Default, 1x (Red Dot/Iron), 2x, 3x, 4x, Sniper/8x
 *  - Gyroscope (same slots, higher values)
 */

const USAGE =
    `🎮 *CALL OF DUTY MOBILE SENSITIVITY*\n\n` +
    `Usage: *$codmsensi <device> [RAM]GB <Android|iOS>*\n\n` +
    `Examples:\n` +
    `• $codmsensi Samsung S23 Ultra 12GB Android\n` +
    `• $codmsensi iPhone 15 Pro Max iOS\n` +
    `• $codmsensi POCO X6 Pro Android\n\n` +
    `_RAM is optional — defaults to 6 GB if not given_`;

function rand(min, max) { return min + Math.floor(Math.random() * (max - min + 1)); }

function generateCODM(ram, isIOS) {
    const tier = ram >= 12 ? 0 : ram >= 8 ? 1 : ram >= 6 ? 2 : 3;

    // Firing Camera (hip-fire) — 0-200
    const camBase = [65, 60, 55, 50][tier];

    // ADS base — 0-200 (decreases per scope level)
    const adsBase = [110, 105, 95, 88][tier];

    // Gyroscope base — 0-200 (generally higher for aim correction)
    const gyroBase = [150, 140, 130, 115][tier];

    return {
        // Firing Camera (hip-fire)
        firingCamera: rand(camBase, camBase + 10),

        // ADS sensitivity
        adsDefault: rand(adsBase,      adsBase + 10),
        ads1x:      rand(adsBase - 15, adsBase - 5),
        ads2x:      rand(adsBase - 25, adsBase - 15),
        ads3x:      rand(adsBase - 35, adsBase - 25),
        ads4x:      rand(adsBase - 45, adsBase - 35),
        adsSniper:  rand(adsBase - 65, adsBase - 50),

        // Gyroscope
        gyroFiring:   rand(gyroBase,      gyroBase + 20),
        gyroDefault:  rand(gyroBase - 10, gyroBase + 10),
        gyro1x:       rand(gyroBase - 20, gyroBase),
        gyro2x:       rand(gyroBase - 35, gyroBase - 15),
        gyro3x:       rand(gyroBase - 50, gyroBase - 30),
        gyro4x:       rand(gyroBase - 65, gyroBase - 45),
        gyroSniper:   rand(gyroBase - 85, gyroBase - 65),
    };
}

async function codmSensiCommand(sock, chatId, message, userMessage) {
    try {
        const args = userMessage.replace(/^\$codmsensi\s*/i, '').trim();
        if (!args) return sock.sendMessage(chatId, { text: USAGE }, { quoted: message });

        const platformMatch = args.match(/\b(android|ios|iphone|ipad)\b/i);
        if (!platformMatch) {
            return sock.sendMessage(chatId, {
                text: `❌ Platform not found. End with *Android* or *iOS*.\n\n${USAGE}`
            }, { quoted: message });
        }

        const platform = platformMatch[0];
        const isIOS    = /ios|iphone|ipad/i.test(platform);
        const ramMatch = args.match(/(\d+)\s*gb/i);
        const ram      = ramMatch ? parseInt(ramMatch[1]) : 6;

        const deviceName = args
            .replace(/\d+\s*gb/i, '')
            .replace(/\b(android|ios|iphone|ipad)\b/i, '')
            .replace(/\s+/g, ' ').trim() || 'Unknown Device';

        if (!isKnownBrand(args)) {
            return sock.sendMessage(chatId, {
                text: `❌ *"${deviceName}"* doesn't look like a real phone model.\n\nPlease use your actual device name.\nExamples: *Samsung S23 Ultra*, *iPhone 15 Pro Max*, *POCO X6 Pro*`
            }, { quoted: message });
        }

        const s = generateCODM(ram, isIOS);

        const text = [
            `🎮 *CALL OF DUTY MOBILE SENSITIVITY*`,
            `━━━━━━━━━━━━━━━━━━━━`,
            `📱 *${deviceName.toUpperCase()}*`,
            `💾 ${ramMatch ? `RAM: ${ram}GB  •  ` : ''}${isIOS ? 'iPhone/iOS' : 'Android'}`,
            `━━━━━━━━━━━━━━━━━━━━`,
            ``,
            `🔥 *FIRING CAMERA*  → *${s.firingCamera}*`,
            ``,
            `🎯 *ADS SENSITIVITY*`,
            `   Default         → *${s.adsDefault}*`,
            `   🔴 1x (Red Dot) → *${s.ads1x}*`,
            `   🔭 2x Scope     → *${s.ads2x}*`,
            `   🔭 3x Scope     → *${s.ads3x}*`,
            `   🔭 4x Scope     → *${s.ads4x}*`,
            `   🎯 Sniper / 8x  → *${s.adsSniper}*`,
            ``,
            `🌀 *GYROSCOPE SENSITIVITY*`,
            `   Firing Camera   → *${s.gyroFiring}*`,
            `   Default ADS     → *${s.gyroDefault}*`,
            `   1x (Red Dot)    → *${s.gyro1x}*`,
            `   2x Scope        → *${s.gyro2x}*`,
            `   3x Scope        → *${s.gyro3x}*`,
            `   4x Scope        → *${s.gyro4x}*`,
            `   Sniper / 8x     → *${s.gyroSniper}*`,
            ``,
            `━━━━━━━━━━━━━━━━━━━━`,
            `_Generated by Daratech_ 🫶`,
        ].join('\n');

        await sock.sendMessage(chatId, { text }, { quoted: message });

    } catch (err) {
        console.error('[codmsensi]', err.message);
        await sock.sendMessage(chatId, { text: '❌ Failed to generate sensitivity.' }, { quoted: message });
    }
}

module.exports = codmSensiCommand;
