'use strict';
const { isKnownBrand } = require('../lib/brandCheck');

/**
 * $pubgsensi <device> [RAM]GB <Android|iOS>
 * Generates PUBG Mobile sensitivity settings.
 *
 * PUBG Mobile sensitivity ranges:
 *  Camera (no-scope / free look) : 0 – 300
 *  ADS (scoped)                  : 0 – 100
 *  Gyroscope                     : 0 – 300
 */

const USAGE =
    `🎮 *PUBG MOBILE SENSITIVITY*\n\n` +
    `Usage: *$pubgsensi <device> [RAM]GB <Android|iOS>*\n\n` +
    `Examples:\n` +
    `• $pubgsensi Samsung S23 Ultra 12GB Android\n` +
    `• $pubgsensi iPhone 15 Pro Max iOS\n` +
    `• $pubgsensi POCO X6 Pro Android\n\n` +
    `_RAM is optional — defaults to 6 GB if not given_`;

function rand(min, max) { return min + Math.floor(Math.random() * (max - min + 1)); }

function generatePUBG(ram, isIOS) {
    // Tier: flagship / high / mid / low
    const tier = ram >= 12 ? 0 : ram >= 8 ? 1 : ram >= 6 ? 2 : 3;

    // Camera (free look / hip-fire) — 0-300
    const camBase   = [145, 135, 125, 110][tier];
    const camOff    = 10;

    // ADS — 0-100
    const adsBase   = [95, 90, 85, 80][tier];

    // Gyroscope base — 0-300
    const gyroBase  = [280, 260, 240, 210][tier];

    return {
        // Camera
        thirdPerson:  rand(camBase,      camBase + camOff),
        firstPerson:  rand(camBase - 15, camBase - 5),
        redDot:       rand(55, 70),
        scope2x:      rand(40, 55),
        scope3x:      rand(30, 45),
        scope4x:      rand(22, 35),
        scope6x:      rand(14, 25),
        scope8x:      rand(8,  18),

        // ADS sensitivity (single value, applies to all scopes in-game)
        ads: rand(adsBase - 5, adsBase),

        // Gyroscope (only shown for Android, or iOS if enabled)
        gyroNoScope:  rand(gyroBase - 20, gyroBase),
        gyroRedDot:   rand(150, 200),
        gyro2x:       rand(110, 160),
        gyro3x:       rand(80,  130),
        gyro4x:       rand(60,  100),
        gyro6x:       rand(40,  70),
        gyro8x:       rand(20,  45),
    };
}

async function pubgSensiCommand(sock, chatId, message, userMessage) {
    try {
        const args = userMessage.replace(/^\.pubgsensi\s*/i, '').trim();
        if (!args) return sock.sendMessage(chatId, { text: USAGE }, { quoted: message });

        const platformMatch = args.match(/\b(android|ios|iphone|ipad)\b/i);
        if (!platformMatch) {
            return sock.sendMessage(chatId, {
                text: `❌ Platform not found. End with *Android* or *iOS*.\n\n${USAGE}`
            }, { quoted: message });
        }

        const platform = platformMatch[0];
        const isIOS    = /ios|iphone|ipad/i.test(platform);
        const ramMatch = args.match(/(\d+)\s*gb/i);
        const ram      = ramMatch ? parseInt(ramMatch[1]) : 6;

        const deviceName = args
            .replace(/\d+\s*gb/i, '')
            .replace(/\b(android|ios|iphone|ipad)\b/i, '')
            .replace(/\s+/g, ' ').trim() || 'Unknown Device';

        if (!isKnownBrand(args)) {
            return sock.sendMessage(chatId, {
                text: `❌ *"${deviceName}"* doesn't look like a real phone model.\n\nPlease use your actual device name.\nExamples: *Samsung S23 Ultra*, *iPhone 15 Pro Max*, *POCO X6 Pro*`
            }, { quoted: message });
        }

        const s = generatePUBG(ram, isIOS);

        const text = [
            `🎮 *PUBG MOBILE SENSITIVITY*`,
            `━━━━━━━━━━━━━━━━━━━━`,
            `📱 *${deviceName.toUpperCase()}*`,
            `💾 ${ramMatch ? `RAM: ${ram}GB  •  ` : ''}${isIOS ? 'iPhone/iOS' : 'Android'}`,
            `━━━━━━━━━━━━━━━━━━━━`,
            ``,
            `📷 *CAMERA SENSITIVITY*`,
            `   3rd Person (No Scope) → *${s.thirdPerson}*`,
            `   1st Person (No Scope) → *${s.firstPerson}*`,
            `   🔴 Red Dot / Holo     → *${s.redDot}*`,
            `   🔭 2x Scope           → *${s.scope2x}*`,
            `   🔭 3x Scope           → *${s.scope3x}*`,
            `   🔭 4x Scope           → *${s.scope4x}*`,
            `   🔭 6x Scope           → *${s.scope6x}*`,
            `   🎯 8x / 15x Scope     → *${s.scope8x}*`,
            ``,
            `🎯 *ADS SENSITIVITY* → *${s.ads}*`,
            ``,
            `🌀 *GYROSCOPE SENSITIVITY*`,
            `   No Scope    → *${s.gyroNoScope}*`,
            `   Red Dot     → *${s.gyroRedDot}*`,
            `   2x Scope    → *${s.gyro2x}*`,
            `   3x Scope    → *${s.gyro3x}*`,
            `   4x Scope    → *${s.gyro4x}*`,
            `   6x Scope    → *${s.gyro6x}*`,
            `   8x Scope    → *${s.gyro8x}*`,
            ``,
            `━━━━━━━━━━━━━━━━━━━━`,
            `_Generated by Daratech_ 🫶`,
        ].join('\n');

        await sock.sendMessage(chatId, { text }, { quoted: message });

    } catch (err) {
        console.error('[pubgsensi]', err.message);
        await sock.sendMessage(chatId, { text: '❌ Failed to generate sensitivity.' }, { quoted: message });
    }
}

module.exports = pubgSensiCommand;
