'use strict';
/**
 * Shared category data used by both $menu and $help
 *
 * Each entry:
 *   slug       — short keyword user types  ($menu movies  /  $help ai)
 *   emoji      — category emoji
 *   title      — display title
 *   cmds[]     — command list shown by $menu <slug>
 *   help[]     — detailed description lines shown by $help <slug>
 */

const CATEGORIES = [
    {
        slug: 'start',
        emoji: '🚀',
        title: 'START HERE',
        cmds: [
            '$ping', '$alive', '$uptime',
            '$menu', '$help',
            '$owner', '$community', '$update', '$autoupdate',
            '$calc', '$settings', '$sudo',
        ],
        help: [
            '$ping                 → check if bot is online',
            '$alive                → bot status message',
            '$uptime               → how long bot has been running',
            '$menu                 → category overview',
            '$menu <category>      → commands in a category',
            '$help                 → this help overview',
            '$help <category>      → full descriptions for a category',
            '$owner                → contact bot owner',
            '$community            → join the Daratech WhatsApp community',
            '$update               → update bot to latest version',
            '$autoupdate on/off    → automatic updates',
            '$calc <expr>          → 🧮 calculator  (e.g. $calc 5*9+2)',
            '$settings             → view bot settings',
            '$sudo                 → owner-only sudo mode',
        ],
    },
    {
        slug: 'ai',
        emoji: '🤖',
        title: 'AI COMMANDS',
        cmds: [
            '── 🤖 Pollinations AI ──',
            '$ai <query>', '$ask <query>',
            '$gpt <query>', '$gpt4o <query>', '$gptlarge <query>', '$gptfast <query>',
            '$gemini <query>', '$mistral <query>', '$qwen <query>',
            '$imagine <prompt>', '$flux <prompt>', '$txt2img <prompt>', '$sora <prompt>',
            '── 🔮 More AI Models ──',
            '$claude <query>', '$deepseek <query>', '$gpt4 <query>',
            '$llama <query>', '$mistralai <query>', '$geminioc <query>',
            '$grok <query>', '$qwenai <query>', '$o1 <query>',
            '── 🌐 Other AI Engines ──',
            '$letmegpt <query>', '$unlimitedai <query>',
            '$gifgemini <query>', '$gifvenice <query>', '$gifpoll <query>',
            '$muslimai <query>',
            '── 🎨 AI Image Generation ──',
            '$giftflux <prompt>', '$gifttxt2img <prompt>', '$magicstudio <prompt>',
            '$animegen <prompt>', '$artgen <prompt>', '$realgen <prompt>',
            '── 🔍 AI Vision ──',
            '$vision (reply to image)',
            '── 📝 AI Utility ──',
            '$transcript <yt url>',
            '$humanize <text>', '$summarize <text>',
            '$rewrite <text>', '$grammar <text>',
        ],
        help: [
            '── 🤖 POLLINATIONS AI (free) ──',
            '$ai <query>           → GPT-4o AI (general purpose)',
            '$ask <query>          → alias for $ai',
            '$gpt / $gpt4o         → GPT-4o advanced',
            '$gptlarge <query>     → GPT-4o Large (more detailed)',
            '$gptfast <query>      → GPT-4o Fast (quicker)',
            '$gemini <query>       → Google Gemini AI',
            '$mistral <query>      → Mistral AI',
            '$qwen <query>         → Qwen Coder AI',
            '$imagine <prompt>     → AI image generation (Flux)',
            '$flux <prompt>        → Flux image generator',
            '$txt2img <prompt>     → text-to-image (Pollinations)',
            '$sora <prompt>        → Cinematic AI image',
            '',
            '── 🔮 MORE AI MODELS ──',
            '$claude <query>       → Claude AI (Anthropic)',
            '$deepseek <query>     → DeepSeek AI',
            '$gpt4 <query>         → GPT-4',
            '$llama <query>        → Meta LLaMA AI',
            '$mistralai <query>    → Mistral AI',
            '$geminioc <query>     → Google Gemini (alternate)',
            '$grok <query>         → Grok AI (xAI)',
            '$qwenai <query>       → Qwen AI (Alibaba)',
            '$o1 <query>           → OpenAI O1 reasoning model',
            '',
            '── 🌐 OTHER AI ENGINES ──',
            '$letmegpt <query>     → LetMeGPT model',
            '$unlimitedai <query>  → UnlimitedAI reasoning model',
            '$gifgemini <query>    → Google Gemini (alternate engine)',
            '$gifvenice <query>    → Venice AI (uncensored responses)',
            '$gifpoll <query>      → Pollinations AI',
            '$muslimai <query>     → Islamic AI — Quran, Hadith & rulings',
            '',
            '── 🎨 AI IMAGE GENERATION ──',
            '$giftflux <prompt>    → Flux image generation (high quality)',
            '$gifttxt2img <prompt> → txt2img (alternate server)',
            '$magicstudio <prompt> → MagicStudio AI image (artistic style)',
            '$animegen <prompt>    → Generate anime-style AI image',
            '$artgen <prompt>      → Generate artistic AI image',
            '$realgen <prompt>     → Generate realistic/photorealistic AI image',
            '',
            '── 🔍 AI VISION ──',
            '$vision (reply to image) → Analyze / describe an image using AI vision',
            '',
            '── 📝 AI UTILITY ──',
            '$transcript <yt url>  → Get full transcript/subtitles of a YouTube video',
            '$humanize <text>      → Rewrite AI-sounding text to sound natural & human',
            '$summarize <text>     → Summarize text into concise bullet points',
            '$rewrite <text>       → Rewrite text for clarity and professionalism',
            '$grammar <text>       → Fix grammar, spelling & punctuation',
            '                        (all 4 also accept a *quoted message*)',
        ],
    },
    {
        slug: 'movies',
        emoji: '🎬',
        title: 'MOVIES & STREAMING',
        cmds: [
            '$movie <title>', '$movie details <id>',
            '$movie dl <id>', '$movie dl <id> 360p',
            '$movietrailer <id>',
            '$trending', '$upcoming', '$schedule',
            '$live', '$livesearch <name>', '$livestream <id>',
            '$anime <title>', '$anime dl <id>',
            '$net9ja <title>',
        ],
        help: [
            '$movie <title>            → search any movie or show',
            '$movie details <id>       → full info + poster image',
            '$movie dl <id>            → show available resolutions',
            '$movie dl <id> 360p       → download by quality name',
            '$movietrailer <id>        → watch official trailer 🎬',
            '$trending                 → 🔥 what is trending now',
            '$upcoming                 → 🗓 upcoming releases',
            '$schedule                 → 📅 weekly airing schedule',
            '$live                     → browse live TV channels',
            '$livesearch <name>        → search a live channel',
            '$livestream <id>          → get stream link',
            '$anime <title>            → search anime titles',
            '$anime dl <id>            → anime download options',
            '$net9ja <title>           → search Net9ja movie database',
        ],
    },
    {
        slug: 'download',
        emoji: '📥',
        title: 'DOWNLOADERS',
        cmds: [
            '── 🎵 YouTube Audio ──',
            '$ytaudio <title/url>', '$ytaudiodoc <title/url>',
            '── 🎬 YouTube Video ──',
            '$ytvideo <title/url>',
            '── 📱 Social Media ──',
            '$tiktok <url>', '$tt <url>',
            '$instagram <url>', '$igdl <url>',
            '$facebook <url>', '$fbdl <url>',
            '$twitter <url>', '$twdl <url>',
            '$pinterestdl <url>', '$pintdl <url>', '$pdl <url>',
            '$douyin <url>',
            '$snackvideo <url>',
            '── 🎧 Music ──',
            '$spotify <title/url>',
            '$soundcloud <url>',
            '── 💾 Files ──',
            '$mediafire <url>',
            '$gdrive <url>',
            '$videy <url>',
            '$webdl <url>',
            '$aio <url>',
            '── 🛠️ Other ──',
            '$apk <app name>',
            '$gitclone <github url>',
            '── 👻 Snapchat ──',
            '$snapchat <url>', '$snap <url>',
            '── 🎵 Playlist ──',
            '$playlist <url>',
        ],
        help: [
            '── 🎵 YOUTUBE AUDIO ──',
            '$ytaudio <title/url>    → YouTube audio as OGG/OPUS audio bubble',
            '$ytaudiodoc <title/url> → YouTube audio sent as downloadable MP3 file',
            '',
            '── 🎬 YOUTUBE VIDEO ──',
            '$ytvideo <title/url>    → YouTube video (720p) as video message',
            '',
            '── 📱 SOCIAL MEDIA ──',
            '$tiktok / $tt <url> → TikTok video without watermark',
            '$instagram <url>     → Instagram post / reel',
            '$igdl <url>          → alias for $instagram (v2 endpoint)',
            '$facebook / $fb <url>→ Facebook video',
            '$fbdl <url>          → alias for $facebook',
            '$twitter / $twdl <url> → Twitter / X video download',
            '$pinterestdl <url>   → Pinterest image / video / GIF',
            '$pintdl / $pdl <url>→ aliases for $pinterestdl',
            '$douyin <url>        → Douyin (Chinese TikTok) video',
            '$snackvideo <url>    → SnackVideo download',
            '',
            '── 🎧 MUSIC ──',
            '$spotify <title/url> → Spotify track download',
            '$soundcloud <url>    → SoundCloud track download',
            '',
            '── 💾 FILE DOWNLOADS ──',
            '$mediafire <url>     → Download any MediaFire file',
            '$gdrive <url>        → Google Drive file (must be public)',
            '$videy <url>         → Videy.co video download',
            '$webdl <url>         → Download any direct image/video/audio/file URL',
            '$aio <url>           → All-in-one (Twitter/X, Facebook, Bilibili…)',
            '',
            '── 🛠️ OTHER ──',
            '$apk <app name>      → Download Android APK by app name',
            '$gitclone <url>      → Download GitHub repo as ZIP',
            '',
            '── 👻 SNAPCHAT ──',
            '$snapchat / $snap <url> → Download Snapchat Spotlight / Story video',
            '',
            '── 🎵 PLAYLIST ──',
            '$playlist <url>      → Download full YouTube playlist as audio (max 10 tracks)',
        ],
    },
    {
        slug: 'search',
        emoji: '🔍',
        title: 'SEARCH',
        cmds: [
            '── 🌐 Web ──',
            '$gsearch <query>', '$gimage <query>', '$get <url>',
            '── 🎵 Music ──',
            '$yts <query>', '$lyrics <song>',
            '$slyrics <query>', '$chord <song>',
            '$hearthis <query>', '$scsearch <query>',
            '── 📱 Social ──',
            '$ttsearch <query>', '$wattpad <query>',
            '$stickersearch <query>',
            '── 📦 Apps & Packages ──',
            '$npmpkg <package>', '$happymod <query>',
            '── 🖼️ Media ──',
            '$wallpaper <query>', '$pinterest <query>',
            '── 📰 News ──',
            '$news',
        ],
        help: [
            '── 🌐 WEB ──',
            '$gsearch <query>      → Google web search (top 6 results)',
            '$gimage <query>       → Google image search',
            '$get <url>            → fetch any image from a URL and send it',
            '',
            '── 🎵 MUSIC ──',
            '$yts / $ytsearch <q>  → YouTube video search (top 7)',
            '$lyrics <song>        → song lyrics (Genius)',
            '$slyrics <query>      → Spotify lyrics search',
            '$chord <song>         → guitar chord tabs',
            '$hearthis <query>     → hearthis.at audio sets search',
            '$scsearch <query>     → SoundCloud track search',
            '',
            '── 📱 SOCIAL / STORIES ──',
            '$ttsearch <query>     → TikTok video search',
            '$wattpad <query>      → Wattpad story search',
            '$stickersearch <query>→ sticker image search',
            '',
            '── 📦 APPS & PACKAGES ──',
            '$npmpkg <package>     → npm package info (version, downloads, links)',
            '$happymod <query>     → Android app / mod search',
            '',
            '── 🖼️ MEDIA ──',
            '$wallpaper <query>    → high-quality wallpaper images',
            '$pinterest <query>    → Pinterest image search',
            '',
            '── 📰 NEWS ──',
            '$news                 → latest tech & general news headlines',
        ],
    },
    {
        slug: 'stalk',
        emoji: '🌐',
        title: 'STALK / LOOKUP',
        cmds: [
            '── 📱 Social Media ──',
            '$ttstalk <username>', '$tiktokstalk <username>',
            '$ghstalk <username>',
            '$igstalk <username>',
            '$twstalk <username>', '$xstalk <username>',
            '$steamstalk <username>',
            '$wachannel <url>',
            '── 🔍 Data Lookup ──',
            '$ipstalk <ip>', '$iplookup <ip>',
            '$npmstalk <package>', '$npmlookup <package>',
            '── 🖥️ Network Tools ──',
            '$whois <domain>',
            '$dns <domain>',
            '$headers <url>',
            '$servercheck <url>',
            '── 📲 WA ID Tools ──',
            '$phone <number>',
            '$lid <lid>',
            '$jid <jid>',
        ],
        help: [
            '── 📱 SOCIAL MEDIA ──',
            '$ttstalk <user>       → TikTok profile (followers, videos, bio)',
            '$ghstalk <user>       → GitHub profile (repos, followers, bio)',
            '$igstalk <user>       → Instagram profile lookup',
            '$twstalk <user>       → Twitter / X profile lookup',
            '$steamstalk <user>    → Steam gaming profile lookup',
            '$wachannel <url>      → WhatsApp channel info & followers',
            '',
            '── 🔍 DATA LOOKUP ──',
            '$ipstalk <ip>         → IP address geolocation & ISP info',
            '$npmstalk <package>   → npm package info (version, owner, stats)',
            '',
            '── 🖥️ NETWORK TOOLS ──',
            '$whois <domain>       → domain WHOIS (owner, registrar, dates, nameservers)',
            '$dns <domain>         → DNS records lookup (A, MX, NS, TXT…)',
            '$headers <url>        → raw HTTP response headers of a server',
            '$servercheck <url>    → check if a website/server is online',
            '',
            '── 📲 WHATSAPP ID TOOLS ──',
            '$phone <number>       → show JID + LID for a phone number',
            '$lid <lid>            → show phone number + JID for a LID',
            '$jid <jid>            → show phone number + LID for a JID',
        ],
    },
    {
        slug: 'sports',
        emoji: '🏆',
        title: 'SPORTS',
        cmds: [
            '── ⚽ Football Live ──',
            '$flivescore / $fls', '$fstream / $fstreaming',
            '── 🔍 Football Search ──',
            '$fplayer <name>', '$fteam <name>', '$fvenue <name>',
            '── 📰 Football Info ──',
            '$fnews / $footballnews', '$fleagues',
            '── 🏆 EPL ──',
            '$eplstand', '$eplmatches', '$eplupcoming / $eplfixtures',
            '── 🇪🇸 La Liga ──',
            '$laligastand', '$laligamatches', '$laligaupcoming / $laligafixtures',
            '── 🇩🇪 Bundesliga ──',
            '$bundesstand / $bundesliga',
            '── 🏀 Basketball ──',
            '$blive / $bball',
            '── 🌍 Multi-Sport ──',
            '$sports', '$scoreboard', '$livescores',
            '$sportsteam <name>', '$sportsplayer <name>',
            '$nbastandings', '$nflstandings', '$soccerstandings',
        ],
        help: [
            '── ⚽ FOOTBALL LIVE ──',
            '$flivescore / $fls         → all live football matches (worldwide)',
            '$fstream / $fstreaming     → football live stream links',
            '',
            '── 🔍 FOOTBALL SEARCH ──',
            '$fplayer <name>            → player profile + photo (e.g. $fplayer messi)',
            '$fteam <name>              → club info + badge (e.g. $fteam arsenal)',
            '$fvenue <name>             → stadium info (e.g. $fvenue wembley)',
            '',
            '── 📰 FOOTBALL INFO ──',
            '$fnews / $footballnews     → latest football news headlines',
            '$fleagues                  → list all supported leagues',
            '',
            '── 🏆 EPL ──',
            '$eplstand                  → Premier League standings table',
            '$eplmatches                → Premier League recent results',
            '$eplupcoming / $eplfixtures→ Premier League upcoming fixtures',
            '',
            '── 🇪🇸 LA LIGA ──',
            '$laligastand               → La Liga standings table',
            '$laligamatches             → La Liga recent results',
            '$laligaupcoming            → La Liga upcoming fixtures',
            '',
            '── 🇩🇪 BUNDESLIGA ──',
            '$bundesstand / $bundesliga → Bundesliga standings table',
            '',
            '── 🏀 BASKETBALL ──',
            '$blive / $bball            → live basketball scores',
            '',
            '── 🌍 MULTI-SPORT ──',
            '$sports / $scoreboard      → live soccer, NBA & NFL scores',
            '$sportsteam <name>         → look up any sports team',
            '$sportsplayer <name>       → look up any sports player',
            '$nbastandings              → NBA standings',
            '$nflstandings              → NFL standings',
            '$soccerstandings           → soccer standings',
        ],
    },
    {
        slug: 'tools',
        emoji: '🔧',
        title: 'TOOLS & UTILITIES',
        cmds: [
            '── 🌐 Web & Screenshot ──',
            '$ss <url>', '$ssweb <url>',
            '$ssphone <url>', '$sstab <url>', '$sspc <url>',
            '$web2zip <url>',
            '── 📄 Documents & Images ──',
            '$topdf <text/url>',
            '$ttp <text>', '$canvas <type> <title>',
            '$createqr <text>', '$genqr <text>',
            '$carbon <code>',
            '$rc <image url>',
            '── 🔗 URL Shorteners ──',
            '$tinyurl <url>', '$cleanuri <url>',
            '$vgd <url>', '$rebrandly <url>',
            '$vurl <url>', '$adfoc <url>', '$ssur <url>',
            '── 👁️ View Once ──',
            '$vv', '$vv2 / $vvdm',
            '── 🌍 Other Tools ──',
            '$weather <city>', '$translate <text> | <lang>',
            '$tts <text>', '$url <link>',
            '$proxy',
            '$imgscan', '$remini', '$removebg',
            '$fact',
            '$tempmail', '$tempmail inbox',
            '$cpuinfo', '$meminfo', '$diskinfo', '$timezone',
        ],
        help: [
            '── 🌐 WEB & SCREENSHOT ──',
            '$ss <url>              → screenshot (web viewport)',
            '$ssphone <url>         → screenshot (mobile viewport)',
            '$sstab <url>           → screenshot (tablet viewport)',
            '$sspc <url>            → screenshot (desktop viewport)',
            '$web2zip <url>         → download a website as a ZIP archive',
            '',
            '── 📄 DOCUMENTS & IMAGES ──',
            '$topdf <text/url>      → generate a PDF from text or a URL',
            '$ttp <text>            → text to stylised picture image',
            '$canvas <type> <title> → canvas card (21 themes: spotify, youtube, tiktok…)',
            '$createqr <text>       → generate QR code image',
            '$carbon <code>         → code snippet to image',
            '$rc <image url>        → AI cloth remover (send image URL of a person)',
            '',
            '── 👁️ VIEW ONCE ──',
            '$vv                    → reveal view-once media in chat (reply to it)',
            '$vv2 / $vvdm           → reveal & send view-once media to owner\'s DM',
            '',
            '── 🌍 OTHER TOOLS ──',
            '$weather <city>        → current weather & forecast',
            '$translate <text> | <lang> → translate text to a language',
            '                        langs: en, fr, es, ar, ha, yo, ig, tpi …',
            '                        e.g. $translate Hello | Hausa',
            '$tts <text>            → text to speech audio',
            '$url <link>            → upload file to URL',
            '── 🔗 URL SHORTENERS ──',
            '$tinyurl <url>         → shorten link with TinyURL',
            '$cleanuri <url>        → shorten link with CleanURI',
            '$vgd <url>             → shorten link with v.gd',
            '$rebrandly <url>       → shorten link with Rebrandly',
            '$vurl <url>            → shorten link with Vurl',
            '$adfoc <url>           → shorten link with Adf.ly (monetised)',
            '$ssur <url>            → shorten link with Ssur.cc',
            '',
            '$proxy                 → fresh list of working proxies',
            '$imgscan               → AI image identification (reply to image)',
            '$remini                → enhance / upscale image quality',
            '$removebg              → remove image background',
            '$fact                  → random fun fact',
            '$tempmail              → generate temporary email address',
            '$tempmail inbox        → check temp email inbox',
            '$cpuinfo / $meminfo    → system resource usage',
            '$diskinfo / $timezone  → disk & time info',
        ],
    },
    {
        slug: 'fun',
        emoji: '😄',
        title: 'FUN & SOCIAL',
        cmds: [
            '── 🎮 Games ──',
            '$truth', '$dare', '$joke',
            '.8ball <question>', '$tictactoe @user', '$hangman', '$trivia',
            '── 💬 Social ──',
            '$rizz', '$flirt @user', '$compliment @user', '$insult @user',
            '$ship @u1 @u2', '$simp @user', '$pair', '$unpair',
            '$quote', '$meme', '$q', '$bored', '$activity',
            '── 🌸 Messages ──',
            '$goodnight', '$shayari', '$roseday',
            '$friendship', '$lovetext', '$heartbreak',
            '$gratitude', '$thankyou',
            '── 🗓️ Seasonal ──',
            '$newyear', '$christmas', '$halloween', '$valentines',
            '$mothersday', '$fathersday', '$bfday', '$gfday',
        ],
        help: [
            '── 🎮 GAMES ──',
            '$truth                → random truth question',
            '$dare                 → random dare challenge',
            '$joke                 → random joke (setup + punchline)',
            '.8ball <question>     → magic 8-ball answer',
            '$tictactoe @user      → play tic-tac-toe',
            '$hangman              → play hangman',
            '$trivia               → trivia question',
            '',
            '── 💬 SOCIAL ──',
            '$rizz / $pickupline  → 😏 rizz / pickup lines',
            '$flirt @user          → poetic flirt message',
            '$compliment @user     → send a compliment',
            '$insult @user         → friendly roast',
            '$ship @u1 @u2         → compatibility percentage',
            '$simp @user           → simp rating card',
            '$pair / $unpair       → couple pairing system',
            '$quote                → wisdom or motivational quote',
            '$meme                 → random meme image',
            '$q                    → reply to any message to generate a quote card',
            '$bored / $activity   → random activity when bored',
            '',
            '── 🌸 MESSAGES ──',
            '$goodnight            → sweet goodnight message',
            '$shayari              → Urdu shayari poetry',
            '$roseday              → Rose Day message',
            '$friendship           → friendship quote',
            '$lovetext             → love quote / message',
            '$heartbreak           → heartbreak quote',
            '$gratitude            → gratitude message',
            '$thankyou             → thank-you message',
            '',
            '── 🗓️ SEASONAL ──',
            '$newyear              → New Year wish',
            '$christmas / $xmas   → Christmas message',
            '$halloween            → Halloween message',
            '$valentines           → Valentine\'s Day message',
            '$mothersday / $mday  → Mother\'s Day message',
            '$fathersday / $fday  → Father\'s Day message',
            '$bfday               → Boyfriend\'s Day message',
            '$gfday               → Girlfriend\'s Day message',
        ],
    },
    {
        slug: 'gaming',
        emoji: '🎮',
        title: 'GAMING SENSITIVITY',
        cmds: [
            '$freefiresensi <device> [RAM]GB <Android|iOS>',
            '$pubgsensi <device> [RAM]GB <Android|iOS>',
            '$codmsensi <device> [RAM]GB <Android|iOS>',
            '$bssensi <device> [RAM]GB <Android|iOS>',
        ],
        help: [
            '$freefiresensi <device> [RAM]GB <Android|iOS>',
            '   → Free Fire sensitivity (General, Red Dot, 2x-4x Scope, Sniper, Free Look, DPI)',
            '',
            '$pubgsensi <device> [RAM]GB <Android|iOS>',
            '   → PUBG Mobile sensitivity (Camera 3rd/1st person, 6 scope levels, ADS, Gyroscope)',
            '',
            '$codmsensi <device> [RAM]GB <Android|iOS>',
            '   → Call of Duty Mobile sensitivity (Firing Camera, ADS 1x-Sniper, Gyroscope)',
            '',
            '$bssensi <device> [RAM]GB <Android|iOS>',
            '   → Blood Strike sensitivity (Camera, ADS Red Dot-Sniper, Gyroscope)',
            '',
            'RAM is optional on all commands — defaults to 6 GB if not given.',
            'Examples:',
            '  $pubgsensi Samsung S23 Ultra 12GB Android',
            '  $codmsensi iPhone 15 Pro Max iOS',
            '  $bssensi POCO X6 Pro Android',
        ],
    },
    {
        slug: 'stickers',
        emoji: '🖼️',
        title: 'STICKERS & IMAGE EFFECTS',
        cmds: [
            '$sticker / $s', '$attp <text>', '$emojimix <e1> <e2>',
            '$steal', '$tgsticker',
            '$blur', '$enhance', '$remini', '$removebg',
            '$screenshot <url>',
            '.1917', '$arena', '$blackpink', '$circle', '$comrade',
            '$devil', '$fire', '$gay', '$glass', '$glitch', '$hacker',
            '$heart', '$horny', '$ice', '$impressive', '$prison',
            '$leaves', '$lgbt', '$light', '$lolice', '$matrix',
            '$metallic', '$namecard', '$neon', '$passed',
            '$snow', '$stupid', '$thunder', '$triggered', '$waste',
        ],
        help: [
            '$sticker / $s         → convert image/video to sticker',
            '$attp <text>          → animated text sticker',
            '$emojimix <e1> <e2>   → mix two emojis into one sticker',
            '$steal                → steal sticker from message',
            '$tgsticker            → search Telegram sticker pack',
            '$blur                 → blur an image',
            '$enhance              → AI enhance / upscale image',
            '$remini               → Remini AI photo enhancer',
            '$removebg             → remove image background',
            '$screenshot <url>     → screenshot a website',
            '.fire/.ice/.neon      → add effects to images',
            '.glitch/.matrix       → special effects',
            '+ more effects        → run $menu stickers to see all',
        ],
    },
    {
        slug: 'crypto',
        emoji: '💰',
        title: 'CRYPTO',
        cmds: [
            '.crypto-price <coin>',
            '.top-crypto',
            '.trending-crypto',
            '.crypto-convert <amt> <from> <to>',
        ],
        help: [
            '.crypto-price <coin>               → live coin price',
            '.top-crypto                        → top 10 coins by market cap',
            '.trending-crypto                   → 🔥 trending coins',
            '.crypto-convert <amt> <from> <to>  → convert between coins',
        ],
    },
    {
        slug: 'anime',
        emoji: '🎌',
        title: 'ANIME',
        cmds: [
            '── 🔍 Search & Info ──',
            '$animeinfo <title>', '$trendinganime', '$animeindo <title>',
            '$kusonime <query>', '$newanime',
            '── 🖼️ Images & Quotes ──',
            '$animu', '$character', '$waifu',
            '$konachan', '$animequote',
            '$charquote <character>', '$showquote <anime>',
        ],
        help: [
            '── 🔍 SEARCH & INFO ──',
            '$animeinfo <title>      → detailed anime info (score, genres, synopsis)',
            '$trendinganime          → 🔥 top currently-airing anime',
            '$animeindo <title>      → search Indonesian-dubbed anime',
            '$kusonime <query>       → search KusoNime for anime downloads',
            '$newanime               → latest anime releases from KusoNime',
            '',
            '── 🖼️ IMAGES & QUOTES ──',
            '$animu                  → random anime image / GIF sticker',
            '$character              → anime character info',
            '$waifu                  → random waifu image',
            '$konachan               → random anime wallpaper from Konachan',
            '$animequote             → random anime character quote',
            '',
            '💡 For streaming anime use $anime <title>  (in Movies)',
        ],
    },
    {
        slug: 'tempgen',
        emoji: '📲',
        title: 'TEMP MAIL & PHONE',
        cmds: [
            '── 📧 Temp Email ──',
            '$tempmail', '$tempmail inbox',
            '── 📞 Temp Phone ──',
            '$tempphone', '$smsinbox [number]',
        ],
        help: [
            '── 📧 TEMP EMAIL ──',
            '$tempmail              → generate a temporary email address',
            '$tempmail inbox        → check temp email inbox',
            '',
            '── 📞 TEMP PHONE / SMS ──',
            '$tempphone             → generate a temporary SMS phone number',
            '$smsinbox              → check SMS inbox (uses your last generated number)',
            '$smsinbox <number>     → check SMS inbox of a specific number',
        ],
    },
    {
        slug: 'language',
        emoji: '📖',
        title: 'LANGUAGE & DEFINE',
        cmds: [
            '$define <word>', '$synonym <word>', '$antonym <word>', '$wordofday',
            '$wiki <topic>', '$wikipedia <topic>',
            '$urban <word>',
        ],
        help: [
            '$define <word>         → dictionary definition + example',
            '$synonym <word>        → synonyms list',
            '$antonym <word>        → antonyms list',
            '$wordofday             → word of the day',
            '$wiki <topic>          → Wikipedia summary + image',
            '$wikipedia <topic>     → alias for $wiki',
            '$urban <word>          → Urban Dictionary slang definition',
        ],
    },
    {
        slug: 'country',
        emoji: '🌍',
        title: 'COUNTRY INFO',
        cmds: [
            '$country <name>',
            '$capital <country>',
            '$flag <country>',
            '$countrytime <country>',
        ],
        help: [
            '$country <name>        → full country info (capital, currency, lang, population)',
            '$capital <country>     → get capital city of a country',
            '$flag <country>        → show country flag image',
            '$countrytime <country> → country timezone(s)',
        ],
    },
    {
        slug: 'animals',
        emoji: '🐾',
        title: 'ANIMALS',
        cmds: [
            '$catfact', '$catimage',
            '$dogfact', '$dogimage',
            '$foximage', '$pandaimage',
            '$koalaimage', '$birb', '$raccoon',
        ],
        help: [
            '$catfact      → random cat fact',
            '$catimage     → random cat image + fact',
            '$dogfact      → random dog fact',
            '$dogimage     → random dog image + fact',
            '$foximage     → random fox image',
            '$pandaimage   → random panda image',
            '$koalaimage   → random koala image',
            '$birb         → random bird image',
            '$raccoon      → random raccoon image',
        ],
    },
    {
        slug: 'food',
        emoji: '🍽️',
        title: 'FOOD & DRINKS',
        cmds: [
            '$recipe <meal>', '$randomrecipe',
            '$cocktail <name>', '$randomcocktail',
        ],
        help: [
            '$recipe <meal>     → search a meal recipe (ingredients + instructions)',
            '$randomrecipe      → random meal recipe',
            '$cocktail <name>   → search a cocktail recipe',
            '$randomcocktail    → alias for $cocktail (random)',
        ],
    },
    {
        slug: 'space',
        emoji: '🌌',
        title: 'SPACE & SCIENCE',
        cmds: [
            '$apod', '$isslocation', '$iss', '$spacefact',
            '$numfact <n>', '$mathfact <n>', '$datefact <m/d>', '$yearfact <yr>',
        ],
        help: [
            '$apod              → NASA Astronomy Picture of the Day',
            '$isslocation / $iss → live International Space Station position',
            '$spacefact         → random space fact',
            '$numfact <n>       → trivia about any number',
            '$mathfact <n>      → math fact about a number',
            '$datefact <m/d>    → historical fact for a date (e.g. $datefact 7/4)',
            '$yearfact <year>   → historical fact for a year',
        ],
    },
    {
        slug: 'texttools',
        emoji: '🔠',
        title: 'TEXT TOOLS',
        cmds: [
            '$reverse <text>', '$morse <text>', '$unmorse <code>',
            '$binary <text>', '$unbinary <bits>',
            '$base64 <text>', '$unbase64 <b64>',
            '$password [len]', '$uuid',
            '$obfuscate <code>',
            '$obfuscate2 <code>',
        ],
        help: [
            '$reverse <text>     → reverse any text',
            '$morse <text>       → convert text to Morse code',
            '$unmorse <code>     → decode Morse code to text',
            '$binary <text>      → convert text to binary',
            '$unbinary <bits>    → decode binary to text',
            '$base64 <text>      → Base64 encode',
            '$unbase64 <b64>     → Base64 decode',
            '$password [len]     → generate secure random password (default 16)',
            '$uuid               → generate a random UUID',
            '$obfuscate <code>   → obfuscate / encrypt JavaScript code (engine v1)',
            '$obfuscate2 <code>  → obfuscate / encrypt JavaScript code (engine v2)',
        ],
    },
    {
        slug: 'ephoto',
        emoji: '🎨',
        title: 'EPHOTO TEXT EFFECTS',
        cmds: [
            '$ephotolist',
            '$ephoto <style> <text>',
            '$ephoto2 <style> <text1> | <text2>',
            '── 🎮 Gaming / Mascot ──',
            'hacker · joker · assassin · gaming · fps · astronaut',
            'dragonball · naruto · minion · dragon · comic',
            '── 💡 Neon / Glow ──',
            'neon · neongalaxy · blueneon · glow · devil · fireworks · futuristic · light',
            '── 🔩 Metal / 3D ──',
            'silver · gold · glitter · metallic · metal3d · titanium · hot · balloon',
            '── 🌌 Nature / Art ──',
            'galaxy · galaxystyle · galaxywrite · stars · watercolor · autumn · leaves · angel · zodiac',
            '── ✍️ Text / Typography ──',
            'glitch · pixel · gradient · gradient3d · typo · logo · effect · write',
            '── 🏖️ Sand / Beach ──',
            'sand · sand3d · sandwrite · beach',
            '── 🎉 Special / Seasonal ──',
            'snow · christmas · birthday · noel · chocolate · football · hollywood',
            'double · glass · foggy · road · wood · embroidery · blackpink · 1917 · cartoon',
        ],
        help: [
            '$ephotolist                → list every available style',
            '$ephoto <style> <text>     → single-text image effect',
            '$ephoto2 <style> <t1>|<t2> → dual-text image effect',
            '',
            'Example: *$ephoto neon DARATECH*',
            'Example: *$ephoto hacker MyName*',
            'Example: *$ephoto2 deadpool DARA | TECH*',
            '',
            '── 🎮 GAMING / MASCOT ──',
            'hacker  joker  assassin  gaming  fps  astronaut  dragonball  naruto  minion  dragon  comic',
            '',
            '── 💡 NEON / GLOW ──',
            'neon  neongalaxy  blueneon  glow  devil  fireworks  futuristic  light',
            '',
            '── 🔩 METAL / 3D ──',
            'silver  gold  glitter  metallic  metal3d  titanium  hot  balloon',
            '',
            '── 🌌 NATURE / ART ──',
            'galaxy  galaxystyle  galaxywrite  stars  watercolor  autumn  leaves  angel  zodiac',
            '',
            '── ✍️ TEXT / TYPOGRAPHY ──',
            'glitch  pixel  gradient  gradient3d  typo  logo  effect  write',
            '',
            '── 🏖️ SAND / BEACH ──',
            'sand  sand3d  sandwrite  beach',
            '',
            '── 🎉 SPECIAL / SEASONAL ──',
            'snow  christmas  birthday  noel  chocolate  football  hollywood',
            'double  glass  foggy  road  wood  embroidery  blackpink  1917  cartoon',
            '',
            '── 🎭 DUAL-TEXT (.ephoto2) ──',
            'deadpool  thor  avengers  marvel  graffiti  graffitigirl  glittertext',
            'vintage  floral  gun  mountain  space  letter  stone  gradient3dlogo',
            'textlogo  metal3dlogo  wolf  mascot  icon  metalglass  shirt  polygon  pencil  woodlogo  team',
        ],
    },
    {
        slug: 'textpro',
        emoji: '✨',
        title: 'TEXTPRO IMAGE STYLES',
        cmds: [
            '$textpro                   (list styles)',
            '$textpro <style> <text>',
            '── ✨ Glitter ──',
            'goldglitter silverglitter blueglitter pinkglitter greenglitter bronzeglitter',
            '── 🌈 Neon & Glow ──',
            'neon neonalt greenneon glowing',
            '── 🔥 Fire & Dark ──',
            'firework lava halloween blood',
            '── 🧊 Ice & Metal ──',
            'ice steel blackmetal chrome metal goldmetal silvermetal rosegold rainbow',
            '── 🎈 Foil Balloons ──',
            'goldfoil pinkfoil bluefoil greenfoil redfoil purplefoil cyanfoil',
            '── 🦸 Themed ──',
            'captain joker robot wolf wolfbw rainbow2 christmas',
        ],
        help: [
            '$textpro                   → list all available styles',
            '$textpro <style> <text>    → generate a styled text image',
            '',
            'Example: *$textpro neon Daratech*',
            'Example: *$textpro goldglitter Happy Birthday*',
            '',
            '── ✨ GLITTER ──',
            'goldglitter  silverglitter  blueglitter  pinkglitter  greenglitter  bronzeglitter',
            '',
            '── 🌈 NEON & GLOW ──',
            'neon  neonalt  greenneon  glowing',
            '',
            '── 🔥 FIRE & DARK ──',
            'firework  lava  halloween  blood',
            '',
            '── 🧊 ICE & METAL ──',
            'ice  steel  blackmetal  chrome  metal  goldmetal  silvermetal  rosegold  rainbow',
            '',
            '── 🎈 FOIL BALLOONS ──',
            'goldfoil  pinkfoil  bluefoil  greenfoil  redfoil  purplefoil  cyanfoil',
            '',
            '── 🦸 THEMED ──',
            'captain  joker  robot  wolf  wolfbw  rainbow2  christmas',
        ],
    },
    {
        slug: 'fonts',
        emoji: '✏️',
        title: 'FONT STYLES',
        cmds: [
            '── ✨ Multi-Style ──',
            '$fantext <text>', '$fantext2 <text>',
            '── 🔤 Single Style ──',
            '$fancy <text>', '$boldtext <text>', '$italic <text>', '$bolditalic <text>',
            '$script <text>', '$fraktur <text>', '$double <text>',
            '$sans <text>', '$mono <text>', '$wide <text>',
            '$smallcaps <text>', '$bubble <text>',
            '$flip <text>', '$mirror <text>',
        ],
        help: [
            '── ✨ MULTI-STYLE ──',
            '$fantext <text>    → show 10 fancy Unicode styles at once',
            '$fantext2 <text>   → show 10 different fancy styles at once',
            '',
            '── 🔤 SINGLE STYLE ──',
            '$fancy <text>      → 𝓯𝓪𝓷𝓬𝔂 script text',
            '$boldtext <text>   → 𝗯𝗼𝗹𝗱 Unicode text',
            '$italic <text>     → 𝘪𝘵𝘢𝘭𝘪𝘤 text',
            '$bolditalic <text> → 𝙗𝙤𝙡𝙙 𝙞𝙩𝙖𝙡𝙞𝙘',
            '$script <text>     → 𝓼𝓬𝓻𝓲𝓹𝓽 style',
            '$fraktur <text>    → 𝔣𝔯𝔞𝔨𝔱𝔲𝔯 Gothic',
            '$double <text>     → 𝕕𝕠𝕦𝕓𝕝𝕖-𝕤𝕥𝕣𝕦𝕔𝕜',
            '$sans <text>       → 𝗌𝖺𝗇𝗌-𝗌𝖾𝗋𝗂𝖿',
            '$mono <text>       → 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎',
            '$wide <text>       → ｗｉｄｅ text',
            '$smallcaps <text>  → ꜱᴍᴀʟʟ ᴄᴀᴘꜱ',
            '$bubble <text>     → ⓑⓤⓑⓑⓛⓔ text',
            '$flip <text>       → flip text ʇxǝʇ',
            '$mirror <text>     → txet rorrim',
        ],
    },
    {
        slug: 'generators',
        emoji: '🎲',
        title: 'GENERATORS & GAMES',
        cmds: [
            '$lorem [n]', '$fakename', '$genemail [name]',
            '$randomnum <min> <max>', '$coinflip', '$diceroll [sides]',
            '$riddle', '$riddleanswer',
            '$wouldyou', '$wyr', '$neverhaveiever', '$nhie',
            '$advice', '$yesno',
        ],
        help: [
            '$lorem [n]               → generate Lorem Ipsum sentences',
            '$fakename / $randomperson → random fake identity',
            '$genemail [name]         → generate a fake email address',
            '$randomnum <min> <max>   → random number in a range',
            '$coinflip / $coin        → flip a coin',
            '$diceroll [sides]        → roll a dice (default d6)',
            '$riddle                  → random riddle puzzle',
            '$riddleanswer            → reveal riddle answer',
            '$wouldyou / $wyr         → Would You Rather question',
            '$neverhaveiever / $nhie  → Never Have I Ever prompt',
            '$advice                  → random life advice',
            '$yesno                   → Yes or No with a GIF',
        ],
    },
    {
        slug: 'bible',
        altSlugs: ['quran'],          // $menu quran → same category
        emoji: '📖',
        title: 'BIBLE & QURAN',
        cmds: [
            '── ✝️ Bible ──',
            '$bible <reference>', '$dailyverse',
            '── ☪️ Quran ──',
            '$quran <surah>:<ayah>', '$quran <surah>',
            '$dailyayah',
            '── 📜 Poetry & Quotes ──',
            '$poem', '$poetry',
            '$animequote', '$kanye', '$kanyequote',
            '$dadjoke', '$chuck', '$programmingjoke',
            '$yomama', '$darkjoke',
        ],
        help: [
            '── ✝️ BIBLE ──',
            '$bible <ref>        → fetch any Bible verse (e.g. $bible john 3:16)',
            '$dailyverse         → verse of the day',
            '',
            '── ☪️ QURAN ──',
            '$quran <s>:<a>      → fetch a Quran verse  e.g. $quran 2:255',
            '$quran <s>          → surah info + verse count  e.g. $quran 18',
            '$dailyayah          → ayah of the day (Arabic + English)',
            '',
            '── 📜 POETRY & QUOTES ──',
            '$poem / $poetry     → random poem from PoetryDB',
            '$animequote         → random anime character quote',
            '$kanye / $kanyequote → random Kanye West quote',
            '$dadjoke            → random dad joke',
            '$chuck              → random Chuck Norris joke',
            '$programmingjoke    → programming / dev joke',
            '$yomama             → yo mama joke',
            '$darkjoke           → dark humour joke',
        ],
    },
    {
        slug: 'converters',
        emoji: '📐',
        title: 'CONVERTERS',
        cmds: [
            '$bmi <kg> <m>', '$age <YYYY-MM-DD>',
            '$celsius <°F>', '$fahrenheit <°C>',
            '$kmtomiles <km>', '$milestokm <mi>',
            '$kgtolbs <kg>', '$lbstokg <lbs>',
        ],
        help: [
            '$bmi <kg> <m>          → BMI calculator + category',
            '$age <YYYY-MM-DD>      → age from birthday in years/months/days',
            '$celsius <°F>          → Fahrenheit to Celsius',
            '$fahrenheit <°C>       → Celsius to Fahrenheit',
            '$kmtomiles <km>        → kilometres to miles',
            '$milestokm <mi>        → miles to kilometres',
            '$kgtolbs <kg>          → kilograms to pounds',
            '$lbstokg <lbs>         → pounds to kilograms',
        ],
    },
    {
        slug: 'media',
        emoji: '🎞️',
        title: 'MEDIA CONVERSION',
        cmds: [
            '$toaudio  (reply to video/audio)',
            '$tovideo  (reply to audio)',
            '$togif    (reply to video)',
            '$toimage  (reply to video)',
            '$tovoice  (reply to audio/video)', '$ptt  (reply to audio/video)',
            '$bassboost (reply to audio)', '$bass (reply to audio)',
            '$jarvis <text>',
        ],
        help: [
            '── 🎞️ MEDIA CONVERSION ──',
            '$toaudio   → reply to a video or audio → converts & sends as MP3 file',
            '$tovideo   → reply to an audio message → wraps audio in an MP4 video',
            '$togif     → reply to a video → converts to animated GIF (first 15s, 10fps)',
            '$toimage   → reply to a video → extracts first frame as a JPEG image',
            '$tovoice / $ptt → reply to audio/video → converts to WhatsApp voice note (PTT)',
            '$bassboost / $bass → reply to audio → apply bass boost effect',
            '$jarvis <text>  → send text as JARVIS (Iron Man) AI voice note',
            '',
            '⚠️ All commands require you to *reply* to a media message.',
            'Large videos may take a moment to process.',
        ],
    },
    {
        slug: 'manga',
        emoji: '📚',
        title: 'MANGA & MANHWA',
        cmds: [
            '$manga <title>',
            '$manga home',
            '$manga popular [page]',
            '$manga latest [page]',
            '$manga genres',
            '$manga genre <slug> [page]',
            '$manga browse [filters]',
            '$manga details <slug>',
            '$manga read <chapter-slug>',
            '$manga dl <chapter-slug>',
            '$manga dls <slug> <from> <to>',
        ],
        help: [
            '$manga <title>              → search manga, manhwa, manhua',
            '$manga home                 → homepage (popularToday + latestUpdates)',
            '$manga popular [page]       → 🔥 popular titles (paginated)',
            '$manga latest [page]        → 🆕 latest releases (paginated)',
            '$manga genres               → full genre list with slugs',
            '$manga genre <slug> [page]  → browse by genre',
            '$manga browse [filters]     → advanced filter',
            '                              e.g. $manga browse genre=action status=ongoing type=manhwa',
            '$manga details <slug>       → full info + complete chapter list',
            '$manga read <ch-slug>       → chapter page image URLs (reader)',
            '$manga dl <ch-slug>         → download chapter as ZIP (max 30 pages)',
            '$manga dls <slug> <f> <t>   → chapter range ZIP (max 3 chapters)',
            '',
            '📖 Powered by RosyScans via RUNFLIX API',
        ],
    },
    {
        slug: 'groups',
        emoji: '🛡️',
        title: 'GROUP MANAGEMENT',
        cmds: [
            // ── Members ──
            '$add @user|<number>',  '$kick @user', '$kickall [@spared]',
            '$ban @user', '$unban @user',
            '$remove <country-code>',
            // ── Roles ──
            '$promote @user', '$promoteall',
            '$demote @user', '$demoteall',
            // ── Mute / warn ──
            '$mute [mins]', '$unmute',
            '.mute-user @user', '.unmute-user @user',
            '$warn @user', '$warnings @user', '$clearwarn @user',
            // ── Tag / broadcast ──
            '$tagall', '$everyone <text>',
            '$hidetag <msg>', '$tag <msg>',
            // ── Group info ──
            '$groupinfo', '$getname', '$getdeskgc', '$jidp',
            '$getppgc', '$setppgc',
            '$listonline', '$listadmins', '$membercount',
            // ── Links ──
            '$linkgc', '$grouplink', '$resetlink',
            '$invite [@user]', '$join <link>',
            // ── Settings ──
            '$opengroup', '$closegroup',
            '$setgname <text>', '$setgdesc <text>',
            '$welcome on/off', '$goodbye on/off',
            '$chatbot on/off', '$botchat <message>',
            '$antilink on/off', '$antitag on/off', '$antibadword on/off',
            '$antileave on/off',
            '$antiimage on/off', '$antivideo on/off',
            '$antisticker on/off', '$antiaudio on/off',
            '$antidemote on/off', '$antipromote on/off',
            '$antimention on/off',
            // ── Group Info Extra ──
            '$banlist', '$gctime',
            '$groupstatus <text>',
            '$groupstatus (reply to image/video/audio)',
            '$groupstatus color <name>',
            '$antigroupmention on/off/set/get',
            '$autosticker on/off',
            '$clean [n]',
            '$purge [n]',
            '$dbstats 👑',
            // ── Moderation ──
            '$del', '$pin 24h|7d|30d', '$unpin',
            // ── Create / leave ──
            '$creategc <name> @users',
            '$leavegc', '$leave',
            // ── Contacts ──
            '$svcontact', '$vcf',
        ],
        help: [
            '── 👥 MEMBERS ──',
            '$add @user|<number>   → add by tag or phone number (comma-separated)',
            '$kick @user           → remove a member (reply or tag)',
            '$kickall [@spared]    → kick all non-admins; tag users to spare them',
            '$ban / $unban @user   → ban or unban a member',
            '$remove <cc>          → kick all non-admin members by country code',
            '                        e.g. $remove 234  (all +234 numbers)',
            '',
            '── 👑 ROLES ──',
            '$promote @user        → make a member admin',
            '$promoteall           → promote ALL members to admin',
            '$demote @user         → remove admin from a member',
            '$demoteall            → demote all regular admins to member',
            '',
            '── 🔇 MUTE / WARN ──',
            '$mute [mins]          → mute group (optional auto-unmute timer)',
            '$unmute               → unmute group',
            '.mute-user @user      → mute a specific member',
            '.unmute-user @user    → unmute a specific member',
            '$warn @user           → warn a member (auto-kick at 3 warnings)',
            '$warnings @user       → check a member\'s warning count',
            '$clearwarn @user      → reset a member\'s warnings',
            '',
            '── 📢 TAG / BROADCAST ──',
            '$tagall               → tag every member',
            '$everyone <text>      → tag all with a custom message',
            '$hidetag <msg>        → tag all silently (non-admins only)',
            '$tag <msg>            → tag & mention all members',
            '',
            '── ℹ️ GROUP INFO ──',
            '$jidp                 → show this group\'s JID',
            '$groupinfo            → full group info card',
            '$getname              → show group name/subject',
            '$getdeskgc            → show group description',
            '$getppgc              → get group profile picture',
            '$setppgc              → set group profile pic (reply to image)',
            '$listonline           → full member list with roles',
            '$listadmins           → list all admins',
            '$membercount          → member count breakdown',
            '',
            '── 🔗 LINKS & JOIN ──',
            '$linkgc / $grouplink  → get group invite link',
            '$resetlink            → revoke & reset the invite link',
            '$invite [@user]       → show link, or DM it to tagged members',
            '$join <link>          → bot joins via invite link (owner only)',
            '',
            '── ⚙️ SETTINGS ──',
            '$opengroup            → allow all members to send messages',
            '$closegroup           → restrict sending to admins only',
            '$setgname <text>      → rename the group',
            '$setgdesc <text>      → update group description',
            '$welcome on/off       → welcome new members',
            '$goodbye on/off       → farewell message on member leave',
            '$chatbot on/off       → enable/disable AI chatbot in this group',
            '$botchat <message>    → chat with the AI directly (chatbot must be on)',
            '                        also: reply to any message with $botchat to discuss it',
            '$antilink on/off      → block links posted by members',
            '$antibadword on/off   → block bad words',
            '$antitag on/off       → block mass @tag spam',
            '$antileave on/off     → post a farewell message when a member leaves',
            '$antiimage on/off     → auto-delete images posted by non-admins',
            '$antivideo on/off     → auto-delete videos posted by non-admins',
            '$antisticker on/off   → auto-delete stickers posted by non-admins',
            '$antiaudio on/off     → auto-delete audio posted by non-admins',
            '$antidemote on/off    → prevent anyone from demoting admins',
            '$antipromote on/off   → prevent non-owner from promoting members',
            '$antimention on/off   → block mass @mention spam',
            '',
            '── ℹ️ GROUP INFO EXTRA ──',
            '$banlist              → show the group ban list',
            '$gctime               → show group creation date & age',
            '',
            '── 📢 GROUP STATUS ──',
            '$groupstatus <text>      → post a text update as a WhatsApp Group Status',
            '$groupstatus (reply)     → reply to image/video/audio to post it as group status',
            '$groupstatus color <name> → set background color by name (red, blue, green…)',
            '$groupstatus color reset  → reset color to default purple',
            'Alias: $gcstatus',
            '',
            '── 🔇 ANTI GROUP MENTION ──',
            '$antigroupmention on/off   → enable/disable @group/@everyone protection',
            '$antigroupmention set delete|kick → set action when triggered',
            '$antigroupmention get      → show current config',
            'Alias: $agm',
            '',
            '── 🖼️ AUTO STICKER ──',
            '$autosticker on/off   → auto-convert images/videos from non-admins to stickers',
            '$autosticker get      → show current status',
            'Aliases: $autos, $asticker',
            '',
            '── 🗑️ CLEAN / PURGE ──',
            '$clean [n]            → delete bot\'s last n messages (default 20, max 100)',
            '$clean all            → delete bot\'s last 100 messages',
            '$clean (reply)        → delete recent messages from that sender',
            'Alias: $purge',
            '',
            '── 📊 DB STATS ──',
            '$dbstats              → show bot data statistics (owner only)',
            '',
            '── 📌 MODERATION ──',
            '$del                  → delete a message (reply to it)',
            '$pin 24h|7d|30d       → pin a replied message',
            '$unpin                → unpin current pinned message',
            '',
            '── 🏗️ CREATE / LEAVE ──',
            '$creategc <name> @u   → create a new group with tagged members',
            '$leavegc              → bot leaves this group (owner only)',
            '$leave                → alias for $leavegc',
            '',
            '── 📇 CONTACTS ──',
            '$svcontact / $vcf     → export all members as a $vcf contact file',
        ],
    },
    {
        slug: 'owner',
        emoji: '⚙️',
        title: 'OWNER / SYSTEM',
        cmds: [
            '$mode public/private',
            '$mode group off/on  (owner)',
            '$mode g off/on      (owner)',
            '$anticall on/off', '$pmblocker on/off',
            '$autoread on/off', '$autoreact on/off',
            '$autotyping on/off', '$autostatus on/off', '$savestatus',
            '$autorecording on/off', '$autoreactstatus on/off',
            '$afk <reason>', '$antidelete on/off', '$antiviewonce on/off', '$vcf',
            '$block @user', '$unblock @user',
            '$bc <message>', '$broadcast <message>',
            '$clearsession', '$cleartmp',
            '$dir', '$dir <path>', '$dir search <name>',
        ],
        help: [
            '$mode public/private    → set who can use the bot globally',
            '$mode group off/on     → disable/enable bot in a specific group',
            '                          off: silences the bot for all non-owners',
            '                          on:  only owner can re-enable it',
            '$anticall on/off        → auto reject incoming calls',
            '$pmblocker on/off     → block unknown private messages',
            '$autoread on/off      → automatically mark messages as read',
            '$autoreact on/off     → automatically react to messages',
            '$autotyping on/off    → show typing indicator',
            '$autostatus on/off    → automatically view statuses',
            '$savestatus           → save status media',
            '$autorecording on/off → show "recording…" indicator automatically in chats',
            '$autoreactstatus on/off → auto-react to contacts\' status updates with emoji',
            '$afk <reason>         → set AFK mode with a reason',
            '$antidelete on/off    → detect and show deleted messages',
            '$antiviewonce on/off  → forward every view-once to your DM',
            '$vcf                  → export group contacts as VCF',
            '$block @user          → block a user',
            '$unblock @user        → unblock a user',
            '$bc <message>         → broadcast message to all contacts',
            '$clearsession         → clear session files',
            '$cleartmp             → clear temp/cache files',
            '$dir                  → view bot root directory listing',
            '$dir <path>           → view a specific folder or file',
            '$dir search <name>    → recursively search files/folders by name',
        ],
    },
];

/**
 * Slug aliases — alternate keywords that resolve to a canonical slug.
 * e.g. `$menu quran` → shows the `bible` (Bible & Quran) category.
 */
const SLUG_ALIASES = {
    quran:   'bible',
    holy:    'bible',
    islam:   'bible',
    koran:   'bible',
};

/**
 * Find a category by slug, alias, or partial title match.
 */
function findCategory(input) {
    if (!input) return null;
    const q = input.toLowerCase().trim();

    // Resolve alias first
    const canonical = SLUG_ALIASES[q] || q;

    let found = CATEGORIES.find(c => c.slug === canonical);
    if (found) return found;
    found = CATEGORIES.find(c => c.slug.startsWith(canonical));
    if (found) return found;
    found = CATEGORIES.find(c =>
        c.title.toLowerCase().split(/[\s&/]+/).some(w => w.startsWith(canonical))
    );
    if (found) return found;
    found = CATEGORIES.find(c =>
        c.slug.includes(canonical) || c.title.toLowerCase().includes(canonical)
    );
    return found || null;
}

CATEGORIES.push({
    slug: 'economy',
    emoji: '💰',
    title: 'ECONOMY',
    cmds: [
        '$balance / $bal / $wallet',
        '$profile [@user or reply]',
        '$daily',
        '$work',
        '$mine',
        '$fish',
        '$rob @user / reply',
        '$pay @user / reply <amount>',
        '$gift @user / reply <amount>',
        '$transfer @user / reply <amount>',
        '$deposit <amount/all>',
        '$withdraw <amount/all>',
        '$gamble <amount/all>',
        '$slots <amount>',
        '$coinflip / $cf <amount> heads/tails',
        '$store / $shop',
        '$buy <item>',
        '$sell <item>',
        '$inventory / $inv / $items',
        '$equip <item>',
        '$upgrade / $up <item>',
        '$use <item>',
        '$battle / $fight / $duel @user / reply [bet]',
        '$estats [@user or reply]',
        '$level / $rank / $xp',
        '$quest',
        '$leaderboard / $richlist / $richest / $lb',
        '$addcoins @user / reply <amount>  (owner)',
        '$removecoins @user / reply <amount>  (owner)',
        '$resetuser @user / reply  (owner)',
        '$boostuser / $boost @user / reply  (owner)',
    ],
    help: [
        '── 💰 EARNING ──',
        '$balance / $bal / $wallet   → check wallet & bank balance',
        '$daily                      → free coins every 24 hours',
        '$work                       → job for coins (1h cooldown)',
        '$mine                       → mine gems/crystals (30m cooldown)',
        '$fish                       → fish for coins (20m cooldown)',
        '$quest                      → daily quest reward (24h cooldown)',
        '',
        '── 🏦 BANKING ──',
        '$deposit <amount/all>       → move coins to bank (safe from rob)',
        '$withdraw <amount/all>      → take coins from bank',
        '',
        '── 🤝 SOCIAL ──',
        '$pay / $transfer @user <amt>  → send coins (also works by replying)',
        '$gift @user <amount>          → gift coins (also works by replying)',
        '$rob @user                    → steal coins — 45% success (2h CD)',
        '',
        '💡 TIP: For rob, pay, gift, battle — you can @mention OR reply to',
        '        someone\'s message instead of mentioning them.',
        '',
        '── 🎲 GAMBLING ──',
        '$gamble <amount/all>        → bet coins (45% win)',
        '$slots <amount>             → slot machine (3-match = jackpot x3–10)',
        '$coinflip / $cf <amt> h/t   → heads or tails bet',
        '',
        '── 🛒 STORE ──',
        '$store / $shop              → view all items & prices',
        '$buy <item>                 → purchase an item',
        '$sell <item>                → sell item back (50% price)',
        '$inventory / $inv / $items  → view owned items + upgrade levels',
        '$equip <item>               → equip weapon / armor / accessory',
        '',
        '📦 STORE TIERS:',
        '  Weapons  — dagger, sword, steelsword, bow, wand, staff, axe,',
        '             spear, hammer, katana, trident, scythe, dragonsword,',
        '             excalibur, godslayer',
        '  Armors   — cloth, shield, leather, ironshield, chainmail,',
        '             platemail, mithril, dragonscale, voidarmor, angelwings',
        '  Accesso. — ring, amulet, bracelet, anklet, cape, dragonring,',
        '             crown, godamulet',
        '  Consumables — potion, megapotion, elixir, xpboost',
        '',
        '── 🔧 UPGRADES ──',
        '$upgrade / $up <item>       → upgrade gear (+10% stats per level, max +10)',
        '                              Cost = item_price × 0.3 × next_level',
        '$use <item>                 → use a consumable (xpboost, potions)',
        '',
        '── ⚔️ BATTLE ──',
        '$battle / $fight / $duel @user [bet] → PvP fight, HP potions auto-used',
        '$estats [@user or reply]    → battle stats, XP, ATK, DEF, Luck',
        '',
        '── 🧑 PROFILE ──',
        '$profile [@user or reply]   → full profile card with gear & upgrade levels',
        '$level / $xp / $rank        → XP progress bar to next level',
        '$leaderboard / $lb          → top 10 richest users',
        '',
        '── 👑 OWNER ONLY ──',
        '$addcoins @user <amt>       → give coins to any user',
        '$removecoins @user <amt>    → deduct coins from any user',
        '$resetuser @user            → wipe a user\'s economy data',
        '$boostuser / $boost @user  → max all gear upgrades (+10) + max stats',
        '',
        '🌟 Bot owner gets unlimited coins, XP, all gear maxed at +10 auto on connect.',
    ],
});

module.exports = { CATEGORIES, findCategory };
